class AddMostColumnsToSurveys < ActiveRecord::Migration
  def change
    add_column :surveys, :birth_year, :integer
    add_column :surveys, :age_group, :integer
    add_column :surveys, :experience_group, :integer
    add_column :surveys, :hours_group, :string
    add_column :surveys, :integer, :string
    add_column :surveys, :member_pro, :boolean
    add_column :surveys, :member_music_org, :boolean
    add_column :surveys, :genre_group_1, :integer
    add_column :surveys, :money_genre_group_1, :integer
    add_column :surveys, :pie_song, :integer
    add_column :surveys, :pie_salary, :integer
    add_column :surveys, :pie_live, :integer
    add_column :surveys, :pie_record, :integer
    add_column :surveys, :pie_session, :integer
    add_column :surveys, :pie_merch, :integer
    add_column :surveys, :pie_teach, :integer
    add_column :surveys, :pie_other, :integer
    add_column :surveys, :compose_inc_direction, :integer
    add_column :surveys, :salary_inc_direction, :integer
    add_column :surveys, :perform_inc_direction, :integer
    add_column :surveys, :record_inc_direction, :integer
    add_column :surveys, :session_inc_direction, :integer
    add_column :surveys, :merch_inc_direction, :integer
    add_column :surveys, :teach_inc_direction, :integer
    add_column :surveys, :rev_youtube, :boolean
    add_column :surveys, :rev_webads, :boolean
    add_column :surveys, :rev_fanfund, :boolean
    add_column :surveys, :rev_fanclub, :boolean
    add_column :surveys, :rev_persona, :boolean
    add_column :surveys, :rev_endorse, :boolean
    add_column :surveys, :rev_acting, :boolean
    add_column :surveys, :rev_corp, :boolean
    add_column :surveys, :rev_sample, :boolean
    add_column :surveys, :rev_honoraria, :boolean
    add_column :surveys, :rev_grants, :boolean
    add_column :surveys, :rev_produce, :boolean
    add_column :surveys, :rev_pubadvance, :boolean
    add_column :surveys, :ascaplus, :boolean
    add_column :surveys, :aarc, :boolean
    add_column :surveys, :afm_2, :boolean
    add_column :surveys, :afm_srsp, :boolean
    add_column :surveys, :afm_aftra, :boolean
    add_column :surveys, :aftra_csp, :boolean
    add_column :surveys, :label_settle, :boolean
    add_column :surveys, :music_inc_share_pct, :float
    add_column :surveys, :income_strata, :string
    add_column :surveys, :income_strata_group, :integer
    add_column :surveys, :emi, :integer
    add_column :surveys, :seasoning_group, :integer
    add_column :surveys, :path_group, :integer
    add_column :surveys, :role_teacher, :boolean
    add_column :surveys, :freq_commercial_radio, :integer
    add_column :surveys, :freq_noncommercial_radio, :integer
    add_column :surveys, :freq_internet_radio, :integer
    add_column :surveys, :freq_satellite_radio, :integer
    add_column :surveys, :freq_cable_radio, :integer
    add_column :surveys, :comfort_net_produce, :integer
    add_column :surveys, :comfort_net_promote, :integer
    add_column :surveys, :comfort_net_distribute, :integer
    add_column :surveys, :comfort_net_collaborate, :integer
    add_column :surveys, :comfort_net_fanconnect, :integer
    add_column :surveys, :gender, :string
    add_column :surveys, :gender_group, :integer
    add_column :surveys, :edu_level_group, :integer
    add_column :surveys, :music_school, :boolean
    add_column :surveys, :zip, :string
    add_column :surveys, :credits_compositions_life, :integer
    add_column :surveys, :credits_recordings_life, :integer
    add_column :surveys, :shows_last_year, :integer
    add_column :surveys, :credits_sessions_life, :integer
    add_column :surveys, :latitude, :float
    add_column :surveys, :longitude, :float
  end
end
